apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-airflow-logs-pvc
  labels:
    app: mlops-airflow-k8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi