apiVersion: v1
kind: Service
metadata:
  name: mlops-airflow-webserver-service
  labels:
    app: mlops-airflow-webserver-deployment
spec:
  type: NodePort
  selector:
    app: mlops-airflow-webserver-deployment
  ports:
  - port: 8080