apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-airflow-postgres-deployment
spec:
  selector:
    matchLabels:
      app: mlops-airflow-postgres-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: mlops-airflow-postgres-deployment
    specs:
      containers:
        - name: postgres
          image: postgres:12
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: airflow
          - name: POSTGRES_USER
            value: airflow
          - name: POSTGRES_DB
            value: airflow